# -*- coding: utf-8 -*-
"""prog1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_pbcqV4Hfw6RuZ3zi-WLTa9EmbcsGIkb
"""

a=1
b=1
c=a+b
print(c)