# -*- coding: utf-8 -*-
"""prog2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ItPP3gnbGRVCbW_u29-IM792yCrkCPM
"""

a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = ((a**2) + (b**2)**(0.50))
print("The hypotenuse is" ,c)